name: students_mac_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aom=3.12.1
  - appnope=0.1.4
  - asttokens=3.0.1
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libcxx=20.1.8
  - libdeflate=1.22
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libsodium=1.0.20
  - libtiff=4.7.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.2.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numexpr=2.14.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytorch=2.5.1
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.3
  - requests=2.32.5
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - threadpoolctl=3.5.0
  - tk=8.6.15
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - chardet==5.2.0
      - click==8.3.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - littleutils==0.2.4
      - lxml==6.0.2
      - multidict==6.7.0
      - nltk==3.9.2
      - ogb==1.3.6
      - outdated==0.2.2
      - propcache==0.4.1
      - regex==2025.11.3
      - seaborn==0.13.2
      - summary==0.2.0
      - sympy==1.13.1
      - torch-geometric==2.7.0
      - torchsummary==1.5.1
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/homebrew/anaconda3/envs/students_mac_env
